# based on https://github.com/cginternals/cmake-init/blob/56e177454d0efb998aab51c13b0dcfbf97b4d9ec/.travis.yml

language: bash

matrix:
  include:
#    - os: linux
#      compiler: clang
#      env: CMAKE_CONFIGURATION=release BUILD_DIR=build
#    - os: osx
#      osx_image: xcode9.1
#      env: CMAKE_CONFIGURATION=release BUILD_DIR=build
    - os: windows
      env:
        - CMAKE_GENERATOR_OVERRIDE="Visual Studio 15 2017 Win64"
        - BUILD_DIR=build
        - CMAKE_CONFIGURATION=release

before_script:
  - eval "${MATRIX_EVAL}"
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then ./windows-setup.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then export MSBUILD_PATH="/c/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/MSBuild/15.0/Bin"; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then export PATH="$MSBUILD_PATH:/c/Program Files/CMake/bin:$PATH"; fi

script:
  - cd gpr
  - mkdir build
  - cd build
  - cmake ../
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then make; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then msbuild /p:Configuration=Release gpr.sln; fi
  - ls
  - ls source/app/gpr_tools
