language: bash

matrix:
  include:
    - os: linux
      compiler: clang
      env:
        - ARTIFACT_PATH=source/app/gpr_tools/gpr_tools
    - os: osx
      osx_image: xcode9.1
      env:
        - ARTIFACT_PATH=source/app/gpr_tools/gpr_tools
    - os: windows
      env:
        - CMAKE_GENERATOR_OVERRIDE="Visual Studio 15 2017 Win64"
        - ARTIFACT_PATH=source/app/gpr_tools/Release/gpr_tools.exe

before_script:
  - eval "${MATRIX_EVAL}"
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then export PATH="$PATH:/c/Program Files/CMake/bin:$(pwd)/make/bin"; fi

script:
  - # build
  - cd $TRAVIS_BUILD_DIR
  - cd gpr
  - mkdir build
  - cd build
  - cmake ../
  - cmake --build . --config Release
  - ls -lR source/app/gpr_tools
  # tests
  - cd $TRAVIS_BUILD_DIR
  - cd gpr/data/tests
  - ./run_tests.sh "$TRAVIS_BUILD_DIR/gpr/build/$ARTIFACT_PATH"

after_script:
#  - cd $TRAVIS_BUILD_DIR
#  - zip "gpr_tools.$TRAVIS_OS_NAME.zip" "./gpr/build/$ARTIFACT_PATH"
#  - curl -sS --upload-file "gpr_tools.$TRAVIS_OS_NAME.zip" "https://transfer.sh/gpr_tools_$TRAVIS_OS_NAME.zip" > transfer.txt
#  - echo -e "\033[0;32m $(cat transfer.txt) \033[0m"
