# based on https://github.com/cginternals/cmake-init/blob/56e177454d0efb998aab51c13b0dcfbf97b4d9ec/.travis.yml

language: bash

matrix:
  include:
    - os: linux
      compiler: clang
      env:
        - CMAKE_CONFIGURATION=release
        - BUILD_DIR=build
        - ARTIFACT_PATH=gpr/build/source/app/gpr_tools/gpr_tools
    - os: osx
      osx_image: xcode9.1
      env:
        - CMAKE_CONFIGURATION=release
        - BUILD_DIR=build
        - ARTIFACT_PATH=gpr/build/source/app/gpr_tools/gpr_tools
    - os: windows
      env:
        - CMAKE_GENERATOR_OVERRIDE="Visual Studio 15 2017 Win64"
        - BUILD_DIR=build
        - CMAKE_CONFIGURATION=release
        - ARTIFACT_PATH=gpr/build/source/app/gpr_tools/Debug/gpr_tools.exe

before_script:
  - eval "${MATRIX_EVAL}"
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then export PATH="$PATH:/c/Program Files/CMake/bin:$(pwd)/make/bin"; fi
  - chmod +x ./cmake-init/configure

script:
  - cd $TRAVIS_BUILD_DIR
  - cd gpr
  - ../cmake-init/configure
  - ../cmake-init/configure $CMAKE_CONFIGURATION
  - cmake --build $BUILD_DIR
#  - mkdir build
#  - cd build
#  - cmake ../
#  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make; fi
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then make; fi
#  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then cmake --build .; fi
  - ls
  - ls -R build
  - ls build/source/app/gpr_tools
  - cd $TRAVIS_BUILD_DIR
  - curl -s --upload-file $ARTIFACT_PATH "https://transfer.sh/gpr_tools_$TRAVIS_OS_NAME"
